yoyogo:
  application:
    name: Alert
    metadata: ""
    server:
      type: "fasthttp"
      address: ":8089"
      max_request_size: 2096157

# alert通过 tag识别节点值
alert:
  test:
    webhook_url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=f53523b2-fb9c-4ec8-a1c3-55ec4c2d2f94
    link_url: http://jcenter-main.easypass.cn/jiankong/d/trpHG7FGk/che-hou-ye-wu-ri-zhi-cha-xun?orgId=1&from=now-1h&to=now&var-app=jishi*&var-level=error&var-host=All&var-msg=*
  znbk:
    webhook_url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=014f19d9-929e-4349-9b0f-ee57d868da9e
    link_url: http://jcenter-main.easypass.cn/jiankong/d/trpHG7FGk/che-hou-ye-wu-ri-zhi-cha-xun?orgId=1&from=now-1h&to=now&var-app=zhineng*&var-level=error&var-host=All&var-msg=*
