yoyogo:
  application:
    name: Alert
    metadata: ""
    server:
      type: "fasthttp"
      address: ":8089"
      max_request_size: 2096157

# alert通过 tag识别节点值
alert:
  test:    # grafana alert 中的 tag
    webhook_url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=f53523b2-fb9c-4ec8-a1c3-55ec4c2d2f94
    link_url: http://localhost:3000/d/lh8kPOQnk/test?orgId=1
  znbk:
    webhook_url:
    link_url:
